# Generated by Django 4.2.7 on 2023-11-29 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_zakaz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zakaz',
            name='items',
        ),
        migrations.CreateModel(
            name='Zacazitems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('tovar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tovar')),
                ('zakaz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.zakaz')),
            ],
        ),
    ]
