# Generated by Django 4.2.7 on 2023-11-29 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_zakaz_items_zacazitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zacazitems',
            name='count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
