# Generated by Django 4.2.7 on 2023-11-29 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_zacazitems_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='zakaz',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='zacazitems',
            name='count',
            field=models.IntegerField(),
        ),
    ]
